CREATE DATABASE PolyOE
GO 
USE PolyOE
GO
CREATE TABLE Users(
	id VARCHAR(20),
	Password VARCHAR(50),
	Fullname NVARCHAR(50),
	Email NVARCHAR(50),
	Admin BIT,
	CONSTRAINT PK_id PRIMARY KEY(id) 
)
SELECT * FROM dbo.Users

SELECT @@VERSION